<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config['row_per_page']=array(
								//'table_name'	=>	20
								 );
$config['table_list']=array( 
        'tblorder'  =>  'Thông tin đặt hàng',
        'tbluser'   =>  'Thành viên',
        'tbldanhmucsanpham' =>  'Danh mục sản phẩm cấp 1',
        'tbldanhmucsanpham2' =>  'Danh mục sản phẩm cấp 2',                
        'tblsanpham'    =>  'Sản phẩm',                                                                            
        'tbldanhmucbaiviet' =>  'Danh mục bài viết cấp 1',  
        'tbldanhmucbaiviet2'    =>  'Danh mục bài viết cấp 2',
        //'tbldanhmucbaiviet3' => 'Danh mục bài viết cấp 3',                                                                
        'tbltintuc'         =>  'Bài viết',        
        'tblslider'      =>  'Ảnh Slider',
        'tbldoitac' =>  'Đối tác',                    
		'tbladmin'			=>	'Administrators',        
        'tblthongtincongty' =>  'Thông tin công ty',                        
        'tblmeta'           =>  'Thông tin Seo',                                        
        'tbllienhe' =>  'Thông tin liên hệ',
        'tblbannerdoc'  =>  'Banner dọc'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   			
		);
//state fields and it's label			
$config['table_field_label']=	array( 
'tblorder'    =>  array(
                'id'    =>  'Mã',                
                'ma'    =>  'Mã đơn hàng',
                'nguoidang' =>  'Người đăng',
                'hoten'   =>  'Họ tên',
                'email' =>  'Email',                            
                'sanpham' =>  'Sản phẩm',
                'diachi' =>  'Địa chỉ',                                
                'tongtien'    =>  'Tổng tiền',                            
                'ngaydang'  =>  'Ngày đăng',
                'ghichu'    =>  'Ghi chú',
                'dienthoai'  =>  'Điện thoại',
                'status'    =>  'Trạng thái'
        ),
'tbluser'   =>  array(
                'id'    =>  'Mã',
                'nguoidang' =>  'Tài khoản',
                'matkhau'   =>  'Mật khẩu',
                'diem'  =>  'Điểm tích',
                'hoten' =>  'Họ tên',
                'diachi'    =>  'Địa chỉ',
                'dienthoai' =>  'Điện thoại',
                'email' =>  'Email',
                'ngaydang'  =>  'Ngày đăng',
                'status'    =>  'Trạng thái'
            ),
'tbldanhmucsanpham' =>  array(
                'id'    =>  'Mã',
                'danhmucsanpham'    =>  'Danh mục sản phẩm',
                'anh'   =>  'Ảnh đại diện',
                'anh_thumb'   =>  'Ảnh resize', 
                'hot'   =>  'Hot',                                                              
                'theh'  =>  'Thẻ Heading',                               
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái',
                'meta_title'    =>  'Meta Title',
                'meta_des'  =>  'Meta Description',
                'keyword'   =>  'Từ khóa'
            ),
'tbldanhmucsanpham2'    =>  array(
                'id'    =>  'Mã',
                'danhmucsanpham'    =>  'Danh mục sản phẩm cấp 1',
                'danhmucsanphamcap2'    =>  'Danh mục sản phẩm cấp 2',
                'home'  =>  'Hiện thị Home',
                'theh'  =>  'Thẻ heading',                                               
                'meta_title'    =>  'Meta Title',
                'meta_des'  =>  'Meta Description',
                'keyword'   =>  'Từ khóa',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái'
            ),
'tbldanhmucsanpham3'    =>  array(
                'id'    =>  'Mã',
                'danhmucsanpham'    =>  'Danh mục sản phẩm cấp 1',
                'danhmucsanphamcap2'    =>  'Danh mục sản phẩm cấp 2',
                'danhmucsanphamcap3'    =>  'Danh mục sản phẩm cấp 3',
                'meta_title'    =>  'Meta Title',
                'meta_des'  =>  'Meta Description',
                'keyword'   =>  'Keyword',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái'
            ),
'tblhang'   =>  array(
                'id'    =>  'Mã',
                'hang'  =>  'Hãng sản xuất',
                'home'  =>  'Hiện thị Home',                
                'theh'  =>  'Thẻ Heading',
                'meta_title'    =>  'Meta Title',
                'meta_des'  =>  'Meta Description',
                'keyword'   =>  'Từ khóa <Hỗ trợ seo>',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái',
            ),                                    
'tblsanpham'    =>  array(
                'id'    =>  'Mã',                
                'danhmucsanpham'    =>  'Danh mục sản phẩm cấp 1',
                'danhmucsanphamcap2'    =>  'Danh mục sản phẩm cấp 2',
                'ma'    =>  'Mã sản phẩm',                                                                                                             
                'ten'   =>  'Tên',
                'dienthoai' =>  'Điện thoại',                                
                'tomtat'   =>  'Thông tin chung',                            
                'noidung'   =>  'Thông số kỹ thuật',                
                'anh'   =>  'Ảnh đại diện',
                'anh_thumb' =>  'Ảnh Resize',                            
                'gia'   =>  'Giá',
                'giakm' =>  'Giá khuyễn mại',                
                'donvitinh' =>  'Đơn vị tính', 
                'noibat'    =>  'Sản phẩm nổi bật',
                'banchay'   =>  'Sản phẩm bán chạy',                                       
                'tinhtrang' =>  'Tình trạng',
                'ngaydang'  =>  'Ngày đăng',
                'giodang'   =>  'Giờ đăng',
                'nguoidang' =>  'Người đăng',
                'view'  =>  'Lượt xem',
                'meta_title'    =>  'Meta Title',
                'meta_des'  =>  'Meta Description',
                'keyword'   =>  'Từ khóa',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái',
                'tag'   =>  'Tag'
            ),
'tblkhoanggia'  =>  array(
                'id'    =>  'Mã',
                'title' =>  'Tiêu đề',
                'giatu' =>  'Giá từ',
                'giaden'    =>  'Giá đến',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái'
            ),
'tblmausac' =>  array(
                'id'    =>  'Mã',
                'tenmau'    =>  'Tên màu',
                'mau' =>  'Mã màu',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái'
            ),
'tbldanhmucphukien' => array(
                'id'    =>  'Mã',
                'danhmucphukien'    =>  'Danh mục phụ kiện cấp 1',
                'theh'  =>  'Thẻ Heading',
                'meta_title'    =>  'Meta Title',
                'meta_des'  =>  'Meta Description',
                'keyword'   =>  'Từ khóa <Hỗ trợ Seo>',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái'
            ), 
'tbldanhmucphukien2' => array(
                'id'    =>  'Mã',
                'danhmucphukien'    =>  'Danh mục phụ kiện cấp 1',
                'danhmucphukiencap2'    =>  'Danh mục phụ kiện cấp 2',
                'theh'  =>  'Thẻ Heading',
                'meta_title'    =>  'Meta Title',
                'meta_des'  =>  'Meta Description',
                'keyword'   =>  'Từ khóa <Hỗ trợ Seo>',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái'
            ),
'tblphukien'    =>array(
                'id'    =>  'Mã',
                'danhmucphukien' => 'Danh mục phụ kiện cấp 1',
                'danhmucphukiencap2' => 'Danh mục phụ kiện cấp 2',
                'ten'   =>  'Tên',
                'anh'   =>  'Ảnh đại diện',
                'anh_thumb' =>  'Ảnh Resize',
                'thongtin1' =>  'Thông tin 1',
                'thongtin2' =>  'Thông tin 2',
                'thongtin3' =>  'Thông tin 3',
                'thongtin4' =>  'Thông tin 4', 
                'thongtin5' =>  'Thông tin 5',
                'baohanh' =>  'Bảo hành',
                'noidung' =>  'Nội dung', 
                'gia' =>  'Giá',
                'donvitinh' =>  'Đơn vị tính', 
                'ngaydang' =>  'Ngày đăng',
                'giodang' =>  'Giờ đăng',
                'meta_title' =>  'Meta Title',
                'meta_des' =>  'Meta Description',
                'keyword'   =>  'Từ khóa <Hỗ trợ Seo>',
                'ordernum' =>  'Thứ tự',
                'status'    =>  'Trạng thái',                
            ),                                                        
'tbldanhmucbaiviet' =>  array(
                'id'    =>  'Mã',
                'danhmucbaiviet'   =>  'Danh mục bài viết cấp 1',                
                'menu'    =>  'Hiện thị Menu',
                'footer'  =>  'Hiện thị Footer',                                
                'theh'  =>  'Thẻ Heading',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                'meta_title' => 'Meta Title',
                'meta_des'   => 'Meta Description',
                'keyword'   =>  'Từ khóa (Hỗ trợ Seo)',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái'
            ),
'tbldanhmucbaiviet2'    =>array(
                'id'    =>  'Mã',
                'danhmucbaiviet'   =>  'Danh mục bài viết cấp 1', 
                'danhmucbaivietcap2'    =>  'Danh mục bài viết cấp 2',                                            
                'theh'  =>  'Thẻ Heading',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                'meta_title' => 'Meta Title',
                'meta_des'   => 'Meta Description',
                'keyword'   =>  'Từ khóa (Hỗ trợ Seo)',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái'

            ),  
'tbldanhmucbaiviet3'    =>array(
                'id'    =>  'Mã',
                'danhmucbaiviet'   =>  'Danh mục bài viết cấp 1', 
                'danhmucbaivietcap2'    =>  'Danh mục bài viết cấp 2',                                            
                'theh'  =>  'Thẻ Heading',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                'meta_title' => 'Meta Title',
                'meta_des'   => 'Meta Description',
                'keyword'   =>  'Từ khóa (Hỗ trợ Seo)',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái'

            ),                                                
'tbltintuc' =>  array(
                'id'    =>  'Mã',                                                                                                                            
                'danhmucbaiviet'   =>  'Danh mục bài viết cấp 1',
                'danhmucbaivietcap2'    =>  'Danh mục bài viết cấp 2',                
                'title' =>  'Tiêu đề',                                                                                                                                        
                'tomtat'    =>  'Tóm tắt',                                                                                                                                                                                        
                'anh'       =>  'Ảnh',
                'anh_thumb' =>  'Ảnh thumb', 
                'footer'  =>  'Hiện thị footer',                           
                'noidung'   =>  'Nội dung',                                                                                                                                                                                        
                'ngaydang'  =>  'Ngày đăng',
                'giodang'   =>  'Giờ đăng',
                'nguoidang' =>  'Người đăng',                                                                                                                                                            
                'view'      =>  'Lượt xem',                                                                                                                                                                                   
                'meta_title' => 'Meta Title',
                'meta_des'   => 'Meta Description',
                'keyword'   =>  'Từ khóa (Hỗ trợ Seo)',               
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái',
                'tag'       =>  'Tags (Các từ ngăn cách nhau bởi dấu phẩy)'
            ),
'tblykienkhachhang' => array(
                'id'    =>  'Mã',
                'hoten' =>  'Họ tên',
                'anh'   =>  'Ảnh đại diện',
                'anh_thumb' => 'Ảnh thumb',
                'tomtat'    =>  'Câu hỏi',
                'noidung'   =>  'Trả lời',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái'
            ),
'tblslider' =>  array(
                'id'    =>  'Mã',
                'title' =>  'Tiêu đề',                               
                'anh'   =>  'Ảnh đại diện. Kích thước (890px x 449px)',                                
                'anh_thumb' =>  'Ảnh Resize',                
                'link'  =>  'Link',                                
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái'
            ),
'tbldoitac' =>  array(
                'id'    =>  'Mã',
                'title'    =>  'Tên đối tác',
                'anh'   =>  'Ảnh đại diện',
                'anh_thumb' =>  'Ảnh resize',
                'link'  =>  'Link',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái'
            ),
'tblquangcao' => array(
                 'id'   =>  'Mã',
                 'title'    =>  'Title',
                 'anh'  =>  'Ảnh đại diện',
                 'anh_thumb'   =>  'Ảnh resize',
                 'link' =>  'Link',
                 'vitri1' =>  'Vị trí 1. Kích thước:250px',
                 'vitri2' =>  'Vị trí 2. Kích thước:650px x 148px',
                 'vitri3' =>  'Vị trí 3. Kích thước:650px x 148px',
                 'vitri4' =>  'Vị trí 4. Kích thước:250px',
                 'vitri5' =>  'Vị trí 5. Kích thước:700px x 300px',
                 'vitri6' =>  'Vị trí 6. Kích thước:438px x 151px',
                 'vitri7' =>  'Vị trí 7. Kích thước:1170px',
                 'ordernum' =>  'Thứ tự',
                 'status'   =>  'Trạng thái'   
            ),                                                                                                								
'tbladmin'   =>  array (
				    'id'			=>'Mã',
				    'username'		=>'Tên đăng nhập',
				    'password'		=>'Mật khẩu',
				    'email'			=>'Email ',
				    'phone'			=>'Phone',
				    'address'		=>'Địa chỉ',
                    'role'		=>'Chọn quyền',
				    'status'		=>'Trạng thái',				    
		      ),           					
'tblthongtincongty' => array(
                'id'    =>  'Mã',                                            
                'tencongty'   =>  'Tên Công ty',                                                                                                                                                                                                                    
                'diachi'    =>  'Địa chỉ',
                'diachi2'    =>  'Văn Phòng',                            
                'dienthoai' =>  'Điện thoại',                
                'email'  =>  'Email',                                            
                'website' =>  'Website',                  
                'logo'  =>  'Logo',
                'anh_thumb' =>  'Ảnh thumb',                                                                                                                                                
                'googleantic'   =>  'Chèn mã Google Analytics',                
                'theh'  =>  'Thẻ Heading',                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			                
            ),              
'tbllienhe' =>array(
                'id'    =>  'Mã',
                'hoten' =>  'Họ tên',
                'diachi'    =>  'Địa chỉ',
                'dienthoai' =>  'Điện thoại',
                'email' =>  'Email',
                'noidung'   =>  'Nội dung',
                'ngaylienhe'    =>  'Ngày liên hệ',
                'status'    =>  'Trạng thái'    
            ), 
            
'tblmeta'   => array(
                'id'    =>  'Mã',
                'title' =>  'Tiêu đề',
                'description'   =>  'Mô tả',
                'keywords'  =>  'Từ khóa'                
            ),
'tblbannerdoc'  =>  array(
                'id'    =>  'Mã',
                'title' =>  'Title',
                'anh'   =>  'Ảnh đại diện',
                'anh_thumb' =>  'Ảnh Resize',
                'url'   =>  'Link',
                'vitri1'    =>  'Hiện thị left',
                'vitri2'    =>  'Hiện thị right',
                'ordernum'  =>  'Thứ tự',
                'status'    =>  'Trạng thái'
            ),
        )    
?>